tests:
  image: 'python:3.10-bullseye'
  stage: test

  before_script:
    - pip install .
    - pip install -r test_requirements.txt
    - useradd testuser
    - cd test
    - python test_data.py

  #    - git pull origin $CI_COMMIT_BRANCH
  script:
    - chmod +rx -R *
    - pwd
    - su testuser -c 'coverage run -m pytest'
    - coverage combine
    - coverage xml
    - coverage-badge
    - coverage report
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
#  rules:
#    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
