tests:
  image: 'python:3.10-bullseye'
  stage: test

  before_script:
    - pip install .
    - pip install -r test_requirements.txt
    - su testuser -c 'mkdir -p $(python -m site --user-site)'
    - su testuser -c 'echo "import coverage" > $(python -m site --user-site)/subprocess_coverage.pth'
    - su testuser -c 'echo "coverage.process_startup()" >> $(python -m site --user-site)/subprocess_coverage.pth'

  #    - git pull origin $CI_COMMIT_BRANCH
  script:

    - chmod +rx -R *
    - su testuser -c 'coverage run -m pytest'
    - coverage combine
    - coverage xml
    - coverage-badge
    - coverage report
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
#  rules:
#    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
