tests:
  image: 'python:3.10-bullseye'
  stage: test

  before_script:
    - pip install .
    - pip install -r test_requirements.txt

  #    - git pull origin $CI_COMMIT_BRANCH
  script:
    - cd test
    - coverage run -m pytest
    - coverage xml
    - coverage-badge
    - coverage report
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
#  rules:
#    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
